/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.daw1.SamuelBarros.Wordle.gui;

import java.awt.Color;
import org.daw1.SamuelBarros.Wordle.clases.GestorMotor;

/**
 *
 * @author samuel505
 */
public class Motor extends javax.swing.JDialog {
GestorMotor g = new GestorMotor();
    /**
     * Creates new form Motor
     */
    public Motor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainjPanel = new javax.swing.JPanel();
        cabezajPanel = new javax.swing.JPanel();
        titulojLabel = new javax.swing.JLabel();
        cuerpojPanel = new javax.swing.JPanel();
        anadirjPanel = new javax.swing.JPanel();
        insertarjPanel = new javax.swing.JPanel();
        anadirjTextField = new javax.swing.JTextField();
        anadirjButton = new javax.swing.JButton();
        estadoInsertarjPanel = new javax.swing.JPanel();
        estadoInsertarjLabel = new javax.swing.JLabel();
        borrarjPanel = new javax.swing.JPanel();
        borradojPanel = new javax.swing.JPanel();
        borrarjTextField = new javax.swing.JTextField();
        borrarjButton = new javax.swing.JButton();
        estadoBorradojPanel = new javax.swing.JPanel();
        estadoBorrarjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainjPanel.setLayout(new java.awt.BorderLayout());

        cabezajPanel.setPreferredSize(new java.awt.Dimension(499, 100));
        cabezajPanel.setLayout(new java.awt.GridBagLayout());

        titulojLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titulojLabel.setText("Gestión motor");
        cabezajPanel.add(titulojLabel, new java.awt.GridBagConstraints());

        mainjPanel.add(cabezajPanel, java.awt.BorderLayout.PAGE_START);

        cuerpojPanel.setLayout(new java.awt.GridLayout(2, 1));

        anadirjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        anadirjPanel.setLayout(new java.awt.GridLayout(2, 1));

        anadirjTextField.setPreferredSize(new java.awt.Dimension(160, 23));
        anadirjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirjTextFieldActionPerformed(evt);
            }
        });
        insertarjPanel.add(anadirjTextField);

        anadirjButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        anadirjButton.setText("Añadir");
        anadirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirjButtonActionPerformed(evt);
            }
        });
        insertarjPanel.add(anadirjButton);

        anadirjPanel.add(insertarjPanel);

        estadoInsertarjPanel.setLayout(new java.awt.GridBagLayout());

        estadoInsertarjLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        estadoInsertarjLabel.setText("errores");
        estadoInsertarjPanel.add(estadoInsertarjLabel, new java.awt.GridBagConstraints());

        anadirjPanel.add(estadoInsertarjPanel);

        cuerpojPanel.add(anadirjPanel);

        borrarjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        borrarjPanel.setLayout(new java.awt.GridLayout(2, 1));

        borrarjTextField.setPreferredSize(new java.awt.Dimension(160, 23));
        borradojPanel.add(borrarjTextField);

        borrarjButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        borrarjButton.setText("Borrar");
        borradojPanel.add(borrarjButton);

        borrarjPanel.add(borradojPanel);

        estadoBorradojPanel.setLayout(new java.awt.GridBagLayout());

        estadoBorrarjLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        estadoBorrarjLabel.setText("errores");
        estadoBorradojPanel.add(estadoBorrarjLabel, new java.awt.GridBagConstraints());

        borrarjPanel.add(estadoBorradojPanel);

        cuerpojPanel.add(borrarjPanel);

        mainjPanel.add(cuerpojPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anadirjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirjTextFieldActionPerformed

    }//GEN-LAST:event_anadirjTextFieldActionPerformed

    private void anadirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirjButtonActionPerformed
        if (!this.anadirjTextField.equals("")||!this.anadirjTextField.equals(" +")) {
             if(g.anadir(this.anadirjTextField.getText())){
                 this.estadoInsertarjLabel.setText("añadido");
             this.estadoInsertarjLabel.setForeground(Color.green);
             }else{
                  this.estadoInsertarjLabel.setText("texto incorrecto");
             this.estadoInsertarjLabel.setForeground(Color.red);
             }
             
        }
    }//GEN-LAST:event_anadirjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Motor dialog = new Motor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirjButton;
    private javax.swing.JPanel anadirjPanel;
    private javax.swing.JTextField anadirjTextField;
    private javax.swing.JPanel borradojPanel;
    private javax.swing.JButton borrarjButton;
    private javax.swing.JPanel borrarjPanel;
    private javax.swing.JTextField borrarjTextField;
    private javax.swing.JPanel cabezajPanel;
    private javax.swing.JPanel cuerpojPanel;
    private javax.swing.JPanel estadoBorradojPanel;
    private javax.swing.JLabel estadoBorrarjLabel;
    private javax.swing.JLabel estadoInsertarjLabel;
    private javax.swing.JPanel estadoInsertarjPanel;
    private javax.swing.JPanel insertarjPanel;
    private javax.swing.JPanel mainjPanel;
    private javax.swing.JLabel titulojLabel;
    // End of variables declaration//GEN-END:variables
}
